// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zbtgwopsqyicoxnwabsq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpidGd3b3BzcXlpY294bndhYnNxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4OTI5NTYsImV4cCI6MjA3NDQ2ODk1Nn0.FHIdOlodx_bIimv0F7yHv2y9QR2QICxyZeQ4HuVtfg8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});